name: test-runner
on:
  push:
    branches:
    - github-actions

jobs:
  build:
    runs-on: [self-hosted, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Print environment
        run: printenv

      - name: .NET SDK info
        run: dotnet --info